### PR TITLE
Add 510 Mhz cpu clockspeed

### PR DESCRIPTION
**Pull request by Anxietytimmy**

### CODE REVIEW

**Comment by jope82** [comment]
Seems pretty low. Is there even a game where that would be usable?

**Comment by Anxietytimmy** [comment]
I have some games that can be used with that clockspeed, but they are few and far between.

**Comment by Anxietytimmy** [comment]
Sonic Mania for instance works with as low as 408 Mhz

**Comment by jope82** [comment]
Thanks for the feedback! I’ll accept this as it should be usable in some games then.

**Pull request merged**
